### PR TITLE
Connect manager bench mark test

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/dirvine/crust/54)

### CODE REVIEW

**Comment by maqi** [comment]
This is to replace the PR : https://github.com/dirvine/crust/pull/12

**Comment by dirvine** [comment]
@maqi  Can you please look at conflicts.

**Comment by inetic** [comment]
Hi ya, I'm gonna just sum up what we've discussed over the private rust channel here. For the benchmark, I don't think it does anything useful. Seems, what it does, it creates two CM nodes and then periodically calls the `connect` method from one to the other, I don't think this is something sensible, nor something we would like to benchmark. On top, there is a sleep_ms in the benchmark which I think reduces its value further.

In the future we might want to add benchmark that tests how quickly a set of nodes can interconnect, but due to limitations in rust's current TCP stack (unable to break from blocking calls) this would just crash the bench so I don't think we should attempt it right now (though we might want to have a crashing test case just to remind us of the limitations).

As discussed and agreed upon with @maqi and Viv, a sensible benchmark right now for us would test a throughput between two nodes.

**Comment by maqi** [comment]
The merging conflict has been resolved.
I have also changed the bench test to measure the throughput between two nodes.

**Comment by dirvine** [comment]
Reviewed files:
- benches/connection_manager.rs @ r5
- src/connection_manager.rs @ r5

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dirvine/crust/54)

**Pull request merged**
